const { ObjectId } = require('mongodb');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const { getCollections, getDatabase } = require('../lib/database');
const { seedDatabase } = require('../lib/seed');

const origins = (process.env.CORS_ORIGINS || 'http://localhost:5173').split(',').map((value) => value.trim()).filter(Boolean);
const secret = () => { if (!process.env.JWT_SECRET) throw Object.assign(new Error('Autenticación no configurada'), { statusCode: 503 }); return process.env.JWT_SECRET; };
function send(res, req, status, value) { const origin = req.headers.origin; if (origin && origins.includes(origin)) res.setHeader('access-control-allow-origin', origin); res.setHeader('vary', 'Origin'); res.setHeader('access-control-allow-methods', 'GET,POST,PUT,PATCH,DELETE,OPTIONS'); res.setHeader('access-control-allow-headers', 'content-type,authorization'); res.setHeader('content-type', 'application/json; charset=utf-8'); res.statusCode = status; res.end(status === 204 ? undefined : JSON.stringify(value)); }
async function readBody(req) { if (req.body && typeof req.body === 'object') return req.body; let raw = ''; for await (const part of req) raw += part; if (!raw) return {}; try { return JSON.parse(raw); } catch { throw Object.assign(new Error('El cuerpo debe ser JSON válido'), { statusCode: 400 }); } }
function serialize(value) { if (!value) return null; const { _id, passwordHash, ...rest } = value; return { id: _id.toString(), ...rest }; }
function currentUser(req) { const token = req.headers.authorization; if (!token?.startsWith('Bearer ')) throw Object.assign(new Error('Autenticación requerida'), { statusCode: 401 }); try { return jwt.verify(token.slice(7), secret()); } catch { throw Object.assign(new Error('Token inválido o vencido'), { statusCode: 401 }); } }
function admin(req) { const user = currentUser(req); if (user.role !== 'ADMIN') throw Object.assign(new Error('No tienes permiso para esta operación'), { statusCode: 403 }); return user; }
function id(value) { return ObjectId.isValid(value) ? new ObjectId(value) : null; }
function recipeFor(message) {
  const text = message.toLowerCase();
  if (text.includes('arroz') && text.includes('pollo')) return { title: 'Arroz con pollo para 4 personas', servings: 4, steps: ['Sofríe cebolla, ajo y pimentón.', 'Agrega el pollo y dóralo.', 'Incorpora arroz, tomate y agua; cocina hasta que esté listo.'], skus: ['arroz-premium', 'pechuga-pollo', 'tomate-chonto', 'cebolla-cabezona', 'ajo', 'pimenton-rojo', 'cilantro'] };
  if (text.includes('pasta') || text.includes('italiana')) return { title: 'Pasta cremosa italiana para 4 personas', servings: 4, steps: ['Sofríe ajo con mantequilla.', 'Mezcla pasta con salsa de tomate y crema.', 'Termina con mozzarella y sirve.'], skus: ['pasta-spaghetti', 'salsa-tomate', 'crema-leche', 'mozzarella', 'ajo', 'mantequilla'] };
  if (text.includes('vegetar')) return { title: 'Bowl vegetariano para 4 personas', servings: 4, steps: ['Cocina lentejas.', 'Saltea verduras con aceite de oliva.', 'Sirve con aguacate y limón.'], skus: ['lentejas', 'espinaca', 'zanahoria', 'pimenton-rojo', 'aguacate-hass', 'aceite-oliva', 'limon-tahiti'] };
  return null;
}
function budgetFrom(message) {
  const match = message.match(/(?:m[aá]ximo|presupuesto|hasta)\s*(?:de\s*)?\$?\s*([\d.]+)/i);
  return match ? Number(match[1].replace(/\./g, '')) : null;
}

async function handler(req, res) {
  if (req.method === 'OPTIONS') return send(res, req, 204, {});
  const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`); const path = url.pathname;
  if (path === '/health') { try { await (await getDatabase()).command({ ping: 1 }); return send(res, req, 200, { status: 'ok', service: 'markecia-api', database: 'connected' }); } catch (error) { console.error('Database health check failed', error?.name, error?.message); return send(res, req, 503, { status: 'degraded', service: 'markecia-api', database: process.env.MONGODB_URI ? 'connection_failed' : 'not_configured', errorType: error?.name || 'UnknownError' }); } }
  const { users, products, carts, orders } = await getCollections();
  if (path === '/api/auth/login' && req.method === 'POST') { const { email, password } = await readBody(req); const user = await users.findOne({ email: String(email || '').toLowerCase() }); if (!user || !password || !(await bcrypt.compare(password, user.passwordHash))) return send(res, req, 401, { error: 'Credenciales inválidas' }); return send(res, req, 200, { token: jwt.sign({ sub: user._id.toString(), email: user.email, role: user.role }, secret(), { expiresIn: '8h' }), user: serialize(user) }); }
  if (path === '/api/auth/me' && req.method === 'GET') { const user = currentUser(req); return send(res, req, 200, { user: serialize(await users.findOne({ _id: id(user.sub) })) }); }
  if (path === '/api/products' && req.method === 'GET') { const q = url.searchParams.get('q') || ''; const category = url.searchParams.get('category'); const filter = { ...(category ? { category } : {}), ...(q ? { $or: ['name', 'brand', 'description'].map((field) => ({ [field]: { $regex: q, $options: 'i' } })) } : {}) }; return send(res, req, 200, { products: (await products.find(filter).sort({ name: 1 }).toArray()).map(serialize) }); }
  const productKey = path.match(/^\/api\/products\/([^/]+)$/)?.[1];
  if (productKey && req.method === 'GET') { const product = await products.findOne({ $or: [{ sku: productKey }, { _id: id(productKey) }] }); return product ? send(res, req, 200, { product: serialize(product) }) : send(res, req, 404, { error: 'Producto no encontrado' }); }
  if (path === '/api/products' && req.method === 'POST') { admin(req); const product = await readBody(req); if (!product.sku || !product.name || !Number.isFinite(product.price) || !Number.isInteger(product.stock)) return send(res, req, 400, { error: 'sku, name, price y stock son obligatorios' }); product.available = product.stock > 0; product.createdAt = new Date(); product.updatedAt = new Date(); try { await products.insertOne(product); return send(res, req, 201, { product: serialize(product) }); } catch { return send(res, req, 409, { error: 'SKU ya existe' }); } }
  if (path === '/api/cart' && req.method === 'GET') { const user = currentUser(req); const cart = await carts.findOne({ userId: id(user.sub) }); return send(res, req, 200, { cart: serialize(cart) || { items: [] } }); }
  if (path === '/api/cart/items' && req.method === 'PUT') { const user = currentUser(req); const { items } = await readBody(req); if (!Array.isArray(items) || items.some((item) => !id(item.productId) || !Number.isInteger(item.quantity) || item.quantity < 1)) return send(res, req, 400, { error: 'items inválidos' }); const found = await products.find({ _id: { $in: items.map((item) => id(item.productId)) } }).toArray(); if (found.length !== items.length || items.some((item) => { const product = found.find((entry) => entry._id.equals(id(item.productId))); return !product || product.stock < item.quantity; })) return send(res, req, 409, { error: 'Inventario insuficiente' }); const stored = items.map((item) => { const product = found.find((entry) => entry._id.equals(id(item.productId))); return { productId: product._id, name: product.name, price: product.price, quantity: item.quantity }; }); await carts.updateOne({ userId: id(user.sub) }, { $set: { items: stored, updatedAt: new Date() }, $setOnInsert: { userId: id(user.sub), createdAt: new Date() } }, { upsert: true }); return send(res, req, 200, { cart: { items: stored.map((item) => ({ ...item, productId: item.productId.toString() })) } }); }
  if (path === '/api/orders' && req.method === 'POST') { const user = currentUser(req); const cart = await carts.findOne({ userId: id(user.sub) }); if (!cart?.items?.length) return send(res, req, 400, { error: 'El carrito está vacío' }); const order = { reference: `MK-${Date.now()}`, userId: id(user.sub), items: cart.items, total: cart.items.reduce((sum, item) => sum + item.price * item.quantity, 0), status: 'RECIBIDO', createdAt: new Date() }; for (const item of cart.items) { if (!(await products.updateOne({ _id: item.productId, stock: { $gte: item.quantity } }, { $inc: { stock: -item.quantity }, $set: { updatedAt: new Date() } })).modifiedCount) return send(res, req, 409, { error: 'Inventario actualizado; revisa el carrito' }); } await orders.insertOne(order); await carts.updateOne({ _id: cart._id }, { $set: { items: [], updatedAt: new Date() } }); return send(res, req, 201, { order: serialize(order) }); }
  if (path === '/api/orders' && req.method === 'GET') { const user = currentUser(req); const filter = user.role === 'ADMIN' ? {} : { userId: id(user.sub) }; return send(res, req, 200, { orders: (await orders.find(filter).sort({ createdAt: -1 }).toArray()).map(serialize) }); }
  if (path === '/api/agent/chat' && req.method === 'POST') { const { message } = await readBody(req); if (!message || typeof message !== 'string') return send(res, req, 400, { error: 'message es obligatorio' }); const recipe = recipeFor(message); const budget = budgetFrom(message); const stopWords = new Set(['quiero', 'para', 'como', 'con', 'una', 'unas', 'unos', 'personas', 'hacer', 'necesito', 'dame', 'maximo']); const terms = message.toLowerCase().split(/[^\p{L}\p{N}]+/u).filter((term) => term.length > 2 && !stopWords.has(term) && !/^\d+$/.test(term)).slice(0, 8); const filter = recipe ? { available: true, sku: { $in: recipe.skus } } : terms.length ? { available: true, $or: terms.flatMap((term) => ['name', 'description', 'category'].map((field) => ({ [field]: { $regex: term, $options: 'i' } }))) } : { available: true }; const selection = (await products.find(filter).sort({ rating: -1, reviews: -1 }).limit(12).toArray()).map(serialize); const subtotal = selection.reduce((sum, product) => sum + product.price, 0); const shipping = subtotal >= 70000 ? 0 : 7900; const total = subtotal + shipping; const withinBudget = budget === null || total <= budget; const recommendations = withinBudget ? selection : []; const reason = recipe ? `seleccioné los ${selection.length} ingredientes disponibles de la receta y los ordené por valoración` : `seleccioné productos disponibles con mejores valoraciones para tu solicitud`; const response = !withinBudget ? `La selección completa cuesta ${new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(total)}, incluido el envío, y supera tu máximo de ${new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(budget)}. No añadí productos al carrito para respetar tu presupuesto.` : recipe ? `${recipe.title} · ${recipe.servings} porciones. Pasos: ${recipe.steps.join(' ')}` : selection.length ? `Preparé una selección completa para tu solicitud.` : 'No encontré productos disponibles para esa solicitud.'; return send(res, req, 200, { response, recipe, recommendations, summary: { reason, subtotal, shipping, total, budget, withinBudget, currency: 'COP', items: selection.map((product) => ({ name: product.name, price: product.price, rating: product.rating })) } }); }
  if (path === '/api/admin/seed' && req.method === 'POST') { admin(req); await seedDatabase(); return send(res, req, 200, { status: 'ok' }); }
  return send(res, req, 404, { error: 'Ruta no encontrada' });
}
module.exports = (req, res) => handler(req, res).catch((error) => send(res, req, error.statusCode || 500, { error: error.statusCode ? error.message : 'Error interno del servidor' }));
